### ISSUE TITLE
Instant crash when opening application

### ISSUE THREAD

**Issue by icemaxx5** [td512/Humble-Trove-Downloader#6]
Hi There, I get the 'connecting to trove' message, then nothing after that and just crashes. 
No firewall on, Windows 10 Pro. 

Any help would be greatly appreciated!
thanks!

**Comment by td512** [comment]
Hey @icemaxx5,

Does the app spit out a JIT exception/violation/etc?

**Comment by icemaxx5** [comment]
no, nothing, it just closes, as quick as it opened.

**Comment by td512** [comment]
> no, nothing, it just closes, as quick as it opened.

I see what you mean. I'll look into it

**Comment by icemaxx5** [comment]
awesome! Thank you! You're doing gods work here! :)

**Comment by td512** [comment]
> awesome! Thank you! You're doing gods work here! :)

I wouldn't say that, but thank you 🙂

**Comment by td512** [comment]
@icemaxx5 found the issue, I've seeded test binaries to the people who test this for me, it'll be fixed in 1.7.1

**Comment by AthanImmortal** [comment]
Hey @td512 Just to say as of 6th Sept 2020 I'm also having this issue. Do you know when 1.7.1 will be released?

Thanks so much for your work on this <3

**Comment by td512** [comment]
@icemaxx5 @AthanImmortal sorry for the delay! It's been fixed and [1.7.1 is now live](https://ltscdn.m6.nz/humble/trove-downloader.exe?version=1.7.1&utm_source=htd-github)

**Comment by AthanImmortal** [comment]
Hmm, I uninstalled the old one and installed the new one and I'm still getting the same issue.
![trove close](https://user-images.githubusercontent.com/70839144/92730567-de02d800-f36b-11ea-8da2-7de00035bc42.gif)

Don't know if this is a factor, but the date modified on the files is all February 2020. 
![trove](https://user-images.githubusercontent.com/70839144/92730300-7a78aa80-f36b-11ea-87fe-c1c097a80294.jpg)

I'm not sure if the executable should have shown a newer date if it had been patched?

**Comment by td512** [comment]
@AthanImmortal I've flushed the CDN. should be good now (hopefully)

**Comment by AthanImmortal** [comment]
> 
> 
> @AthanImmortal I've flushed the CDN. should be good now (hopefully)

It launches now. The download size was different, and the program reports as version 1.7.1 in the windows programs list too.

Thanks for your work on this matey.

![image](https://user-images.githubusercontent.com/70839144/92794380-766a7e00-f3a7-11ea-9e46-be5b151b2314.png)

**Comment by td512** [comment]
No worries! If you need to report anything else, you know what to do!
